INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES ('G');
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES ('PG');
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES ('PG-13');
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES ('R');
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES ('NC-17');

INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES ('Комедия');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES ('Драма');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES ('Мультфильм');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES ('Триллер');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES ('Документальный');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES ('Боевик');

INSERT INTO PUBLIC.USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('a@a.a', 'login2', 'name2', '2022-06-06');
INSERT INTO PUBLIC.USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('b@b.b', 'login3', 'name3', '2022-06-02');
INSERT INTO PUBLIC.USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('c@c.c', 'login4', 'name4', '2022-06-04');
INSERT INTO PUBLIC.USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('d@d.d', 'login5', 'name5', '2022-06-05');
INSERT INTO PUBLIC.USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('e@e.e', 'login6', 'name6', '2022-06-11');

INSERT INTO PUBLIC.FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ('film1', 'description1', '2022-06-09', 120, 1);
INSERT INTO PUBLIC.FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ('film2', 'description2', '2022-06-09', 120, 2);
INSERT INTO PUBLIC.FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ('film3', 'description3', '2022-06-16', 11, 3);
INSERT INTO PUBLIC.FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ('film4', 'description4', '2022-06-07', 200, 4);
INSERT INTO PUBLIC.FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ('film5', 'description5', '2022-06-10', 90, 5);
